server:
  port: 9000

spring:
  application:
    name: authservice
  datasource:
    url: jdbc:postgresql://postgres:5432/userdatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_ISSUER_URI}/oauth2/jwks

logging:
  level:
    org:
      springframework:
        security: DEBUG
